name: Trigger the CI workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trigger_docker_build:
    uses: "./.github/workflows/build_docker.yml"
    with:
      # if this is a pull request, use the pull request number as the tag, otherwise set it to "latest"
      tag: ${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || 'latest' }}

  trigger_builds:
    needs: trigger_docker_build
    uses: "./.github/workflows/build_linux.yml"
    with:
      image: ${{ needs.trigger_docker_build.outputs.image }}
      tag: ${{ needs.trigger_docker_build.outputs.tag }}
